name: Frontend CI

on:
  push:
    branches: [ main, development, add-test ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main, development ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Type check
      working-directory: ./frontend
      run: npm run type-check
      
    - name: Run linting
      working-directory: ./frontend
      run: npm run lint:check
      
    - name: Check code formatting
      working-directory: ./frontend
      run: npm run format:check
      
    - name: Run tests
      working-directory: ./frontend
      run: npm run test:ci:basic
      
    - name: Build application
      working-directory: ./frontend
      run: npm run build
      
    - name: Generate coverage report
      working-directory: ./frontend
      run: npm run test:coverage
      continue-on-error: true
        
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: frontend-test-results-node-${{ matrix.node-version }}
        path: |
          frontend/coverage/
          frontend/.next/
        retention-days: 7
